// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GooglePlayServicesConstantsClass
{
        public const string achievement_got_to_level_20 = "CgkIm7-ZseEMEAIQBw"; // <GPGSID>
        public const string achievement_got_to_level_10 = "CgkIm7-ZseEMEAIQBg"; // <GPGSID>
        public const string leaderboard_high_scores = "CgkIm7-ZseEMEAIQAQ"; // <GPGSID>
        public const string achievement_swiped_and_made_a_road = "CgkIm7-ZseEMEAIQBA"; // <GPGSID>
        public const string achievement_watched_a_video = "CgkIm7-ZseEMEAIQAw"; // <GPGSID>
        public const string achievement_got_to_level_5 = "CgkIm7-ZseEMEAIQBQ"; // <GPGSID>

}

